services:
  - type: web
    name: smart-shopping-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node scripts/deploy.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: REACT_APP_API_URL
        sync: false 